### ISSUE TITLE
Support ESLint via npm script

### ISSUE THREAD

**Issue by ianjmacintosh** [ianjmacintosh/usdgal#3]

**Comment by ianjmacintosh** [comment]
Someone broke typescript-eslint 🤦 

```
$ npm run lint

> usdgal@0.0.0 lint
> eslint .


Oops! Something went wrong! :(

ESLint: 9.15.0

TypeError: Error while loading rule '@typescript-eslint/no-unused-expressions': Cannot read properties of undefined (reading 'allowShortCircuit')
Occurred while linting /workspaces/usdgal/src/App.tsx
    at Object.create (/workspaces/usdgal/node_modules/eslint/lib/rules/no-unused-expressions.js:75:13)
    at create (/workspaces/usdgal/node_modules/typescript-eslint/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions.js:28:32)
    at Object.create (/workspaces/usdgal/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:31:20)
    at createRuleListeners (/workspaces/usdgal/node_modules/eslint/lib/linter/linter.js:944:21)
    at /workspaces/usdgal/node_modules/eslint/lib/linter/linter.js:1082:84
    at Array.forEach (<anonymous>)
    at runRules (/workspaces/usdgal/node_modules/eslint/lib/linter/linter.js:1013:34)
    at #flatVerifyWithoutProcessors (/workspaces/usdgal/node_modules/eslint/lib/linter/linter.js:1911:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (/workspaces/usdgal/node_modules/eslint/lib/linter/linter.js:1993:49)
    at Linter._verifyWithFlatConfigArray (/workspaces/usdgal/node_modules/eslint/lib/linter/linter.js:2082:21)
```

There's apparently a fix in canary but when I try to install it, I get a dependency error

**Comment by ianjmacintosh** [comment]
I'm going to wait for the typescript-eslint team to fix

**Comment by ianjmacintosh** [comment]
Done
